### ISSUE TITLE
"[Makefile:116: Check_NifH_like] Error 255" in when running make inside FilterAuids

### ISSUE THREAD

**Issue by ndombrowski** [jdmagasin/nifH-ASV-workflow#10]
I was testing the pipeline and the first step to GatherAsvs runs perfectly fine with the example data.

However, when running make in the FilterAuids folder, I run into an error that is linked to an issue with classifyNifH.sh found [here](https://github.com/jdmagasin/nifH_amplicons_DADA2/blob/0e6b1eb60d9770e44a16e8bffd74cca182e0f6b4/scripts.ancillary/Post_pipeline/CheckNifHLike/classifyNifH.sh). 

This is the content of log.18July2023.txt:
>>>> Comparing ASVs to positive/negative nifH examples in GenBank <<<<<
This step compares the ASVS to positive and negative nifH examples classified by a 2020
run of ARBitrator (Heller et al. 2014). Filtering ASVs based on the relative strengths
of their hits to positive vs. negative examples is done later by filterAuids.R.
make: *** [Makefile:116: Check_NifH_like] Error 255

Looking more into the log files inside Check_NifH_like.tmp I get the following:
Missing /home/user/nifH_amplicons_DADA2/scripts.ancillary/Post_pipeline/CheckNifHLike/scripts/classifyNifH.helper.R or /home/user/nifH_amplicons_DADA2/scripts.ancillary/Post_pipeline/CheckNifHLike/scripts/classifyNifH.helper2.R which should have been distributed with this tool.

After looking for the files, the issue I am running into is that classifyNifH.helper.R exists but classifyNifH.helper2.R does not. To solve this I replaced inside of the classifyNifH.sh script:
`if [ ! -f "$RHELP" ] || [ ! -f "$RHELP2" ] ; then`
with 
`if [ ! -f "$RHELP" ] && [ ! -f "$RHELP2" ] ; then`

My question would be if that is sufficient or whether classifyNifH.helper2.R is needed for anything essential and if so, could it be provided?

Thanks for any input!

**Comment by jdmagasin** [comment]
Good morning Nina,

Thanks for the email and for using our tools!  I just pushed the missing
file to the nifH_amplicons_DADA2. (I.e. to the pipeline, not the workflow.)
  scripts.ancillary/Post_pipeline/CheckNifHLike/scripts/classifyNifH.helper2.R

AYour workaround would have worked (if you are not using the optional
positives FASTA file).  Or you could have removed
 "|| [ ! -f "$RHELP2" ]" .

Best regards,
  Jonathan
