### ISSUE TITLE
Missing mafft in the environment yaml

### ISSUE THREAD

**Issue by ndombrowski** [jdmagasin/nifH-ASV-workflow#11]
Dear @jdmagasin , 

I noticed a small issue when running the makefile inside of AnnotateAuids.

Running this with the default installation setup returns an error: "Loading Classify_NifH_Clusters/auid.filtered.clusters.map ...This file is empty.".  Going through the log files, it turns out that the error is connected to an issue with "/home/user/nifH_amplicons_DADA2/bin/assignNifHclustersToNuclSeqs.sh: line 113: mafft: command not found"

The error seems to be resolved by adding mafft to the conda environment and might be useful to also integrate into the environment yaml file.

Best,
Nina

**Comment by jdmagasin** [comment]
Thank you for looking into this!  Yes, adding mafft to your environment
will solve the problem.

I  just pushed new .yml files that include mafft to both the pipeline
(nifH_amplicons_DADA2) and the post-pipeline workflow (nifH-ASV-workflow).
Additionally, in the  pipeline:
   assignNifHclustersToNuclSeqs.sh now checks for all its dependencies at
the start
   Installation/check_installation.R now checks for mafft (if run with
argument "ancillary")
