### ISSUE TITLE
An error in installing nifh-ASV-workflow

### ISSUE THREAD

**Issue by guangingmai** [jdmagasin/nifH-ASV-workflow#12]
Hi, I got an error while installing the nifh-ASV-workflow. The error messages are as follow:
`Preparing transaction: done                                                                                                    
Verifying transaction: done                                                                                                    
Executing transaction: done                                                                                                    
ERROR conda.core.link:_execute(951): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.11-r43hdfd78af_1'.                                                                                                               
Rolling back transaction: done                                                                                                 
class: LinkError                                                                                                               
message:                                                                                                                       
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.11-r43hdfd78af_1                               
location of failed script: /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/.bioconductor-genomeinfodbdata-post-link.sh                                                                                                            
==> script messages <==                                                                                                        
<None>                                                                                                                         
==> script output <==                                                                                                          
stdout:                                                                                                                        
stderr: ++ dirname -- /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/installBiocDataPackage.sh    
+ SCRIPT_DIR=/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages   
+ json=/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json                                                                                                                          
++ yq '."genomeinfodbdata-1.2.11".fn' /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json                                                                                           
+ FN='"GenomeInfoDbData_1.2.11.tar.gz"'                                                                                        
+ IFS=                                                                                                                         
+ read -r value                                                                                                                
++ yq '."genomeinfodbdata-1.2.11".urls[]' /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json                                                                                       
+ URLS+=($value)                                                                                                               
+ IFS=                                                                                                                         
+ read -r value                                                                                                                
+ URLS+=($value)                                                                                                               
+ IFS=                                                                                                                         
+ read -r value                                                                                                                
+ URLS+=($value)                                                                                                               
+ IFS=                                                                                                                         
+ read -r value                                                                                                                
++ yq '."genomeinfodbdata-1.2.11".md5' /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"2a4cbfc2031992fed3c9445f450890a2"'
+ STAGING=/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/share/genomeinfodbdata-1.2.11
+ mkdir -p /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/share/genomeinfodbdata-1.2.11
+ TARBALL='/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/share/genomeinfodbdata-1.2.11/"GenomeInfoDbData_1.2.11.tar.gz"'
+ SUCCESS=0
+ for URL in '${URLS[@]}'
++ tr -d '"'
++ echo '"https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz"'
+ URL=https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz
++ echo '"2a4cbfc2031992fed3c9445f450890a2"'
++ tr -d '"'
+ MD5=2a4cbfc2031992fed3c9445f450890a2
+ curl -L https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) Recv failure: Connection reset by peer

return code: 35

kwargs:
{}

Traceback (most recent call last):
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 61, in main_subshell
    exit_code = do_call(args, parser)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 205, in do_call
    result = getattr(module, func_name)(args, parser)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/notices/core.py", line 127, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/cli/main_env_create.py", line 178, in execute
    result[installer_type] = installer.install(
                             ^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/env/installers/conda.py", line 63, in install
    unlink_link_transaction.execute()
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/core/link.py", line 355, in execute
    self._execute(
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/core/link.py", line 971, in _execute
    raise CondaMultiError(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.11-r43hdfd78af_1
location of failed script: /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: ++ dirname -- /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages
+ json=/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.11".fn' /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json
+ FN='"GenomeInfoDbData_1.2.11.tar.gz"'
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.11".urls[]' /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.11".md5' /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"2a4cbfc2031992fed3c9445f450890a2"'
+ STAGING=/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/share/genomeinfodbdata-1.2.11
+ mkdir -p /clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/share/genomeinfodbdata-1.2.11
+ TARBALL='/clusterfs/node3/guangingmai/software/miniconda3/envs/nifH_ASV_workflow/share/genomeinfodbdata-1.2.11/"GenomeInfoDbData_1.2.11.tar.gz"'
+ SUCCESS=0
+ for URL in '${URLS[@]}'
++ tr -d '"'
++ echo '"https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz"'
+ URL=https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz
++ echo '"2a4cbfc2031992fed3c9445f450890a2"'
++ tr -d '"'
+ MD5=2a4cbfc2031992fed3c9445f450890a2
+ curl -L https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) Recv failure: Connection reset by peer

return code: 35

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/clusterfs/node3/guangingmai/software/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
             ^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 105, in main
    return conda_exception_handler(main, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 388, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 21, in __call__
    return self.handle_exception(exc_val, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 62, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 78, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 84, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/exceptions.py", line 1270, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/logging/__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/logging/__init__.py", line 1695, in handle
    maybe_record = self.filter(record)
                   ^^^^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/logging/__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/gateways/logging.py", line 64, in filter
    record.msg = record.msg % record.args
                 ~~~~~~~~~~~^~~~~~~~~~~~~
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/__init__.py", line 125, in __repr__
    errs.append(e.__repr__())
                ^^^^^^^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/__init__.py", line 79, in __repr__
    return f"{self.__class__.__name__}: {self}"
                                        ^^^^^^
  File "/clusterfs/node3/guangingmai/software/miniconda3/lib/python3.12/site-packages/conda/__init__.py", line 83, in __str__
    return str(self.message % self._kwargs)
               ~~~~~~~~~~~~~^~~~~~~~~~~~~~
ValueError: unsupported format character 'T' (0x54) at index 2257
`
It seems that it encounter an error while installing the genomeinfodbdata-1.2.11, but i have no idea how to fix. Can you give some suggestions?

**Comment by jdmagasin** [comment]
Thanks @guangingmai for logging the issue (and for using our tools!:)

I just cloned nifH-ASV-worfkflow and successfully created the conda environment using mamba:
```
   mamba env create --file environment_nifH_ASV_workflow.yml
```

Your output shows `curl: (35) Recv failure: Connection reset by peer` when it tries to get the database.  So maybe there is some kind of network error.  I do not see any error when I do the following (from an interactive shell):
```
curl -L https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz -O
```
Does this curl command succeed for you from a normal interactive shell?  If not, then perhaps there is a network/SSL/curl problem.

Also, it looks like you submitted a job script to your cluster to create the conda environment.  Is this correct?  If so, then can you please instead try to install the workflow using a "normal" interactive shell.  (Both to clone the GitHub repository and then to use conda (or mamba) to create the environment.)

Please note that you should set up the DADA2 pipeline before the workflow:  Clone [nifH_amplicons_DADA2](https://github.com/jdmagasin/nifH_amplicons_DADA2) and set up the pipeline environment DADA2_nifH, and update your PATH as described in the pipeline installation document. Since you only mentioned the error for the workflow, I wonder if you installed the pipeline yet.  (If not, you will have problems later because your PATH will not include our tools.)

**Comment by guangingmai** [comment]
Hi @jdmagasin thank you for your prompt reply. I have sucessfully installed the nifh-ASV-workflow with mamba while installing it with conda for the first time. I have alreadly installed the nifh_amplicons_DADA2 and set up the pipeline environment. Now i will follow the steps mentioned in the manuscript. Thanks.
